### ISSUE TITLE
Codepen link not clickable

### ISSUE THREAD

**Issue by UstymUkhman** [blueedgetechno/blueweb#6]
Hi @blueedgetechno , you have a cool portfolio website!

I've notice a tiny issue on desktop (1920 x 1080): in the footer, the codepen icon is noy clickable due to the `.grecaptcha-badge` element that covers it partially. I'm not trying to be rude, but that might be something you'd like to improve.

Cheers!

**Comment by yashash1511** [comment]
yes

**Comment by blueedgetechno** [comment]
Thanks
